baseURL = "https://testingrostislavgureckysite.netlify.app"
defaultContentLanguage = "cs"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "cs-cz"
metaDataFormat = "yaml"
summaryLength = 20
title = "Finanční poradce Brno | Rostislav Gurecký"
[languages.cs]
contentDir = "content"
languageName = "Čeština"
weight = 1
[languages.cs.params]
locale = "cs_CZ"
[[menu.main]]
name = "Úvod"
url = "/#intro"
weight = 1
[[menu.main]]
identifier = "btn"
name = "Chci pomoc"
url = "/mam-zajem"
weight = 6
[[menu.main]]
name = "Kontakt"
url = "/#vizitka"
weight = 4
[[menu.main]]
name = "Články"
url = "/clanky"
weight = 5
[[menu.main]]
name = "Proč já"
url = "/#proc-ja"
weight = 3
[[menu.main]]
name = "Co umím"
url = "/#dovednosti"
weight = 2
[params]
domain = "https://rostislavgurecky.cz"
googleAnalyticsId = "G-TK03J36LZX"
siteDescription = "Finanční poradce pro Brno s více jak dvacetiletou zkušeností. Hypotéky | Pojištění | Investice | Energie "
[params.contact.address]
ZIP = "602 00"
city = "Brno-sever"
link = "https://en.mapy.cz/zakladni?x=16.6151281&y=49.2023964&z=17&source=addr&id=8907726"
street = "Traubova 10"
[params.contact.email]
corporate = "rostislav.gurecky@zfpa.cz"
personal = "r.gurecky@seznam.cz"
[params.contact.telephone]
formatted = "+420 777 581 730"
raw = "+420777581730"
[sitemap]
filename = "sitemap.xml"
