# basic site settings
title = "Rostislav Gurecky"
baseURL = "https://testingrostislavgureckysite.netlify.app"

# language settings
languageCode = "cs-cz"
defaultContentLanguage = "cs"

# disabling taxonomy generator
disableKinds = ["taxonomy", "term"]

# data settings
enableRobotsTXT = true
metaDataFormat = "yaml"

# sitemap output
[sitemap]
filename = "sitemap.xml"

[params]
    domain = "https://rostislavgurecky.cz"
    googleAnalyticsId = "UA-155090268-1"
[params.footer]
    [params.footer.brand]
        logo = "/images/noltio-logo.png"
        logoAlt = "Noltio, s.r.o. logo"
        link = "https://noltio.com/"
        targetBlank = true

[menu]
    [[menu.main]]
        name = "Úvod"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Co umím"
        url = "/#dovednosti"
        weight = 2
    [[menu.main]]
        name = "Proč já"
        url = "/#proc-ja"
        weight = 3
    [[menu.main]]
        name = "Články"
        url = "/clanky"
        weight = 4
    [[menu.main]]
        name = "Kontakt"
        url = "/#vizitka"
        weight = 5
    [[menu.main]]
        name = "Chci pomoc"
        url = "/mam-zajem"
        weight = 6
        identifier = "btn"
    

[languages]
    [languages.cs]
        languageName = "Čeština"
        contentDir = "content"
        weight = 1
        [languages.cs.params]
            locale = "cs_CZ"
