---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Úvodní stránka
  create: all
  match: _index.md
- type: directory
  path: content/clanky
  label: Blog
  create: all
  match: "**/*"
  templates:
  - seznam-clanku
  - clanek
- type: directory
  path: content
  label: Formulář
  create: all
  match: mam-zajem.md
- type: directory
  path: ''
  label: Config!
  create: all
  match: config.toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.74.3
