---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: baseURL
  label: baseURL
- type: text
  name: languageCode
  label: languageCode
- type: text
  name: defaultContentLanguage
  label: defaultContentLanguage
- type: list
  name: disableKinds
  label: disableKinds
- type: boolean
  name: enableRobotsTXT
  label: enableRobotsTXT
- type: text
  name: metaDataFormat
  label: metaDataFormat
- type: field_group
  name: sitemap
  label: sitemap
  fields:
  - type: text
    name: filename
    label: filename
- type: field_group
  name: params
  label: params
  fields:
  - type: text
    name: domain
    label: domain
  - type: text
    name: googleAnalyticsId
    label: googleAnalyticsId
  - type: field_group
    name: footer
    label: footer
    fields:
    - type: field_group
      name: brand
      label: brand
      fields:
      - type: file
        name: logo
        label: logo
      - type: text
        name: logoAlt
        label: logoAlt
      - type: text
        name: link
        label: link
      - type: boolean
        name: targetBlank
        label: targetBlank
- type: field_group
  name: menu
  label: menu
  fields:
  - type: field_group_list
    name: main
    label: main
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
- type: field_group
  name: languages
  label: languages
  fields:
  - type: field_group
    name: cs
    label: cs
    fields:
    - type: text
      name: languageName
      label: languageName
    - type: text
      name: contentDir
      label: contentDir
    - type: number
      name: weight
      label: weight
    - type: field_group
      name: params
      label: params
      fields:
      - type: text
        name: locale
        label: locale
